name: Build an upload server
on:
  push:
    branches: ["main"]
    paths:
      - server/**
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run find-and-replace to remove slashes
        uses: mad9000/actions-find-and-replace-string@5
        id: remove-slashes
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'
      - name: Build and push the image
        working-directory: ./server/
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PAT }} ghcr.io
          docker build . -t ghcr.io/httprafa/pol-it-car:${{ steps.remove-slashes.outputs.value }} --platform linux/arm/v7
          docker push ghcr.io/httprafa/pol-it-car:${{ steps.remove-slashes.outputs.value }}