name: Build an upload server
on:
  push:
    branches: ["main"]
    paths:
      - server/**
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run find-and-replace to remove slashes
        uses: mad9000/actions-find-and-replace-string@c752ea3069b46f62702ff335bf57ea6fa769ed5b
        id: remove-slashes
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'
      - name: Authenticate
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./server/
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/httprafa/pol-it-car:${{ steps.remove-slashes.outputs.value }}