name: Build an upload server
on:
  push:
    branches: ["main"]
    paths:
      - server/**
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-user-static
          version: 1.0
      - name: Run find-and-replace to remove slashes
        uses: mad9000/actions-find-and-replace-string@c752ea3069b46f62702ff335bf57ea6fa769ed5b
        id: remove-slashes
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'
      - name: Authenticate
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and Push image
        working-directory: ./server/
        run: |
          docker buildx build \
            --file Dockerfile \
            --platform linux/arm/v7 \
            --tag ghcr.io/httprafa/pol-it-car:${{ steps.remove-slashes.outputs.value }} \
            --push .